### ISSUE TITLE
Violation of CC-BY-SA license

### ISSUE THREAD

**Issue by 983** [Deleplace/programming-idioms#55]
The CC-BY-SA license requires attribution, but currently the code snippets are misattributed to the user that created the idiom instead of the user that submitted the code.

**Comment by Deleplace** [comment]
The UI does have imperfections, lack of clarity, and incomplete contribution information.

We have 2 distinct entities : each Idiom contains a list of Implementations. It is correct to say idiom X was created by user Y, but it should not look as if user Y wrote all the implementations in X.

Each Implementation has (a) a creator, (b) a username who last edited it and (c) a history log of all its edits with all usernames.  (a) and (b) are currently not shown on the main detail page, you have to click on the [Edit implementation] button to see them. (c) exists somewhere in the database, it is currently hidden because of nasty bugs and unfinished UI ; you can see a kind of log by accessing directly an URL like http://www.programming-idioms.org/history/38 (where 38 would be the idiom ID).

Obviously the situation could and should be improved. A first step would be to display explicitly, together with an implementation, the username of its creator.

Thanks 983 for bringing this problem to my attention!

**Comment by Deleplace** [comment]
The History pages are now public, kind of like in Wikipedia. On an idiom page, click [Actions] > [Idiom history].
For new edits, Editor name is shown in History.
For older edits, Editor name is invisible but with some extra work we should be able to extract it from database soon.
